version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install flake8
      - run:
          name: Run linter
          command: |
            . venv/bin/activate
            flake8 myapp

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install django
      - run:
          name: Run Django tests
          command: |
            . venv/bin/activate
            python manage.py test

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
      - test:
          requires:
            - lint
