version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install django
      - run:
          name: Run Django tests
          command: |
            . venv/bin/activate
            python manage.py test

workflows:
  version: 2
  test:
    jobs:
      - test
